### ISSUE TITLE
Release of v0.2

### ISSUE THREAD

**Issue by Forzooo** [Forzooo/cryptographyComplements#2]
Planned tasks:

- [x] Euclidean Algorithm
- [x] Extended Euclidean Algorithm
- [ ] Shanks's Babystep-Giantstep Algorithm
- [ ] Chinese remainder theorem
- [ ] Pohlig–Hellman algorithm

**Tasks below** won't be done until I finish, the task above.

- [ ] Complete code revision for v0.2
- [ ] Bug fixes

**Comment by Forzooo** [comment]
The following issue can be seen on the [documentation](https://cryptographycomplements.readthedocs.io/general/planned.html).
